---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.101.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_docs
        args:
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--path-to-file=README.md
          - --hook-config=--create-file-if-not-exist=true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint-docker
        args:
          - "--disable"
          - "MD013"
          - "--ignore"
          - terraform
          - "--fix"

  - repo: https://github.com/mattlqx/pre-commit-ruby
    rev: v1.3.6
    hooks:
      - id: rubocop
        args: ["--autocorrect"]

  - repo: https://github.com/rhysd/actionlint.git
    rev: v1.7.7
    hooks:
      - id: actionlint-docker

  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your repo
        entry: bash -c '.github/bin/trufflehog'
        language: system
        stages: ["pre-commit", "pre-push"]
