inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

plugins: rubocop-rspec

RSpec/ExampleLength:
  Max: 10

RSpec/NestedGroups:
  Max: 4

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
