inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

require: rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/**'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'

RSpec/ExampleLength:
  Enabled: false
