class TradeTariff::CreateTradeTariffKey
  CLIENT_ID_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789".freeze
  CLIENT_ID_LENGTH = 18
  CLIENT_ID_PREFIX = "TT".freeze
  SECRET_LENGTH = 48

  def call(organisation_id, description = nil, scopes = %w[read write])
    trade_tariff_key = TradeTariffKey.new
    trade_tariff_key.organisation_id = organisation_id
    trade_tariff_key.client_id = generate_client_id
    trade_tariff_key.secret = generate_random_secret
    trade_tariff_key.scopes = scopes
    trade_tariff_key.description = description || "Autogenerated on #{Time.zone.now.utc.iso8601}"

    trade_tariff_key.save!
    trade_tariff_key
  end

private

  def generate_client_id
    client_id = CLIENT_ID_PREFIX
    CLIENT_ID_LENGTH.times do
      client_id += CLIENT_ID_CHARS[Kernel.rand(CLIENT_ID_CHARS.length)]
    end
    client_id
  end

  def generate_random_secret
    SecureRandom.hex(SECRET_LENGTH / 2)
  end
end
