# frozen_string_literal: true

class TradeTariff::CreateTradeTariffKey
  API_KEY_TYPE = "API_KEY"

  CreateResult = Struct.new(:trade_tariff_key, :client_secret, keyword_init: true)

  def initialize(identity_client: nil, api_gateway_client: nil)
    @identity_client = identity_client || Identity::ClientCredentialsApi.new
    @api_gateway_client = api_gateway_client || Aws::APIGateway::Client.new
  end

  def call(organisation_id, description = nil, scopes = %w[read write])
    usage_plan_id = TradeTariffDevHub.trade_tariff_usage_plan_id
    identity_token = TradeTariffDevHub.identity_api_key
    if usage_plan_id.blank? || identity_token.blank?
      raise ArgumentError, "Something went wrong. Please contact #{TradeTariffDevHub.application_support_email} for assistance."
    end

    creds = @identity_client.create!(scopes)
    trade_tariff_key = TradeTariffKey.new(
      organisation_id: organisation_id,
      client_id: creds.client_id,
      scopes: scopes,
      description: description || "Autogenerated on #{Time.zone.now.utc.iso8601}",
      enabled: true,
    )
    trade_tariff_key.secret = nil # Not stored; shown once via client_secret in result

    begin
      create_in_api_gateway(trade_tariff_key, usage_plan_id)
      associate_to_usage_plan(trade_tariff_key, usage_plan_id)
    rescue StandardError
      rollback(creds&.client_id, trade_tariff_key&.api_gateway_id)
      raise
    end
    trade_tariff_key.save!
    CreateResult.new(trade_tariff_key: trade_tariff_key, client_secret: creds.client_secret)
  end

private

  def create_in_api_gateway(trade_tariff_key, _usage_plan_id)
    name = api_gateway_key_name_for(trade_tariff_key)
    response = @api_gateway_client.create_api_key(
      name: name,
      value: trade_tariff_key.client_id,
      enabled: true,
    )
    trade_tariff_key.api_gateway_id = response.id.presence || raise("Failed to create API key")
  end

  def api_gateway_key_name_for(trade_tariff_key)
    org = Organisation.find(trade_tariff_key.organisation_id)
    safe_org = org.organisation_name.to_s.gsub(/[^\p{Alnum}\s-]/i, "").truncate(40).squish
    date_part = Time.current.utc.strftime("%Y%m%d")
    prefix = trade_tariff_key.client_id[0..7]
    base = "#{safe_org}-#{date_part}-#{prefix}"
    base.presence || "key-#{prefix}"
  end

  def associate_to_usage_plan(trade_tariff_key, usage_plan_id)
    trade_tariff_key.usage_plan_id = usage_plan_id
    @api_gateway_client.create_usage_plan_key(
      key_id: trade_tariff_key.api_gateway_id,
      key_type: API_KEY_TYPE,
      usage_plan_id: usage_plan_id,
    )
  end

  # If we created a Cognito client or API key, delete them so we don't leave orphaned resources.
  def rollback(client_id, api_gateway_id)
    if api_gateway_id.present?
      begin
        @api_gateway_client.delete_api_key(api_key: api_gateway_id)
      rescue Aws::APIGateway::Errors::NotFoundException
        # Already gone
      rescue StandardError => e
        Rails.logger.error("[CreateTradeTariffKey] Failed to delete API key #{api_gateway_id}: #{e.message}")
      end
    end
    if client_id.present?
      begin
        @identity_client.delete(client_id)
      rescue StandardError => e
        Rails.logger.error("[CreateTradeTariffKey] Failed to delete Cognito client #{client_id}: #{e.message}")
      end
    end
  end
end
