class Ott::CreateOttKey
  CLIENT_ID_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789".freeze
  CLIENT_ID_LENGTH = 17
  CLIENT_ID_PREFIX = "OTT".freeze
  SECRET_LENGTH = 48

  def call(organisation_id, description = nil, scopes = %w[read write])
    ott_key = OttKey.new
    ott_key.organisation_id = organisation_id
    ott_key.client_id = generate_client_id
    ott_key.secret = generate_random_secret
    ott_key.scopes = scopes
    ott_key.description = description || "Autogenerated on #{Time.zone.now.utc.iso8601}"

    ott_key.save!
    ott_key
  end

private

  def generate_client_id
    client_id = CLIENT_ID_PREFIX
    CLIENT_ID_LENGTH.times do
      client_id += CLIENT_ID_CHARS[Kernel.rand(CLIENT_ID_CHARS.length)]
    end
    client_id
  end

  def generate_random_secret
    SecureRandom.hex(SECRET_LENGTH / 2)
  end
end
