class Organisation < ApplicationRecord
  has_paper_trail

  has_many :users, dependent: :destroy
  has_many :api_keys, dependent: :destroy

  enum :status, {
    unregistered: 0,
    authorised: 1,
    pending: 2,
    rejected: 3,
  }

  def self.from_profile!(government_gateway_profile)
    find_or_initialize_by(organisation_id: government_gateway_profile["bas:groupId"]).tap do |organisation|
      if organisation.new_record?
        organisation.description = "Autogenerated on #{Time.zone.now.iso8601}"
        organisation.status = :unregistered

        organisation.save!
      end
    end
  end
end
