name: ci

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  TERRAFORM_VERSION: 1.13.4
  PYTHON_VERSION: 3

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - uses: trade-tariff/trade-tariff-tools/.github/actions/setup-tflint@main
      - uses: trade-tariff/trade-tariff-tools/.github/actions/setup-terraform-docs@main
      - uses: trade-tariff/trade-tariff-tools/.github/actions/setup-ssh@main
        with:
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
      - run: cd terraform/ && terraform init -backend=false -reconfigure
      - run: pip install pre-commit
      - run: pre-commit run --all-files
      - run: bundle exec brakeman

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: tariff_dev_hub_test
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rspec
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/tariff_dev_hub_test"
