name: Deploy to development

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    if: contains(github.event.pull_request.labels.*.name, 'needs-deployment') || github.event_name == 'workflow_dispatch'
    uses: trade-tariff/trade-tariff-tools/.github/workflows/deploy-ecs.yml@main
    with:
      app-name: tariff-dev-hub
      environment: development
    secrets:
      scp-password: ${{ secrets.SCP_PASSWORD }}
      scp-username: ${{ secrets.SCP_USERNAME }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
      ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
      test-flavour: fpo
