name: Deploy to staging

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: trade-tariff/trade-tariff-tools/.github/workflows/deploy-ecs.yml@main
    with:
      app-name: tariff-dev-hub
      environment: staging
      test-flavour: fpo
    secrets:
      scp-password: ${{ secrets.SCP_PASSWORD }}
      scp-username: ${{ secrets.SCP_USERNAME }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
      ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
